" ----------
" Vim Config
" ----------
"
"
" How this works:
"
" This file is minimal.  Most of the vim settings and initialization is in
" several files in .vim/init.  This makes it easier to find things and to
" merge between branches and repos.
"
" Please do not add configuration to this file, unless it *really* needs to
" come first or last, like Pathogen and sourcing the machine-local config.
" Instead, add it to one of the files in .vim/init, or create a new one.


" Pathogen (This must happen first.)
" --------

filetype off                    " Avoid a Vim/Pathogen bug
call pathogen#helptags()
call pathogen#infect()
" call pathogen#runtime_append_all_bundles()
execute pathogen#infect()
syntax on
filetype plugin indent on


set nocompatible                " Don't maintain compatibility with vi
filetype plugin indent on

set backspace=2 " make backspace work like most other apps

"set background=dark

"colorscheme atom-dark
syntax on
colorscheme onedark
filetype plugin indent on


" Source initialization files
" ---------------------------

runtime! init/**.vim

let g:go_fmt_command = "goimports"

" Jump to the main window.
autocmd VimEnter * wincmd p

autocmd StdinReadPre * let s:std_in=1

" Machine-local vim settings - keep this at the end
" --------------------------
silent! source ~/.vimrc.local
